pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:KenjiMobutu@bitbucket.org/kenjimobutu/prid-2324-a11.git
          - cd prid.git
          - git push --mirror git@github.com:github.com/KenjiMobutu/PRID.git