pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare bitbucket.org/kenjimobutu/prid-2324-a11.git
          - cd prid-2324-a11.git
          - git push --mirror git@github.com:KenjiMobutu/PRID.git
